---
- name: Ensure Requirements are Present
  apt:
    state: present
    name:
      - postgresql
      - redis-server
      - libpq-dev
      - python3
      - python3-pip
      - python3-venv
      - python3-dev
      - build-essential
      - libxml2-dev
      - libxslt1-dev
      - libffi-dev
      - libpq-dev
      - libssl-dev
      - zlib1g-dev
      - git
      - libldap2-dev
      - libsasl2-dev
      - libssl-dev
